### ISSUE TITLE
本地图片问题

### ISSUE THREAD

**Issue by xixilalaha** [Magic-zhu/we-canvas#1]
你好，合成本地图片时，他提示图片获取失败，the server responded with a status of 500 (HTTP/1.1 500 Internal Server Error)，报500的错误。且相对路径绝对路径都试过了，但是都有问题，请问你知道该怎么处理么

**Comment by Magic-zhu** [comment]
不好意思 太忙没顾上,原来没有写本地图片,已经改好了
